### model
model_name_or_path: CausalLM/miniG
adapter_name_or_path: saves/miniG/lora/sft

### method
finetuning_type: lora

### dataset
task: mmlu_test  # choices: [mmlu_test, ceval_validation, cmmlu_test]
template: fewshot
lang: en
n_shot: 5

### output
save_dir: saves/miniG/lora/eval

### eval
batch_size: 4
